import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useTheme } from '../context/ThemeContext';
import { MoonIcon, SunIcon, MagnifyingGlassIcon, ScaleIcon, LanguageIcon, SparklesIcon } from '@heroicons/react/24/outline';
import settings from '../config/settings';

const faqs = [
  {
    question: 'What exactly does Knowledge Horizon do?',
    answer:
      'We monitor the global scientific literature every week for new publications relevant to asbestos and talc litigation. Each report is AI-analyzed and curated by experts, so you get a clear picture of what\u2019s being published and what it means for your cases.',
  },
  {
    question: 'Where does the science come from?',
    answer:
      'Primary literature is sourced from PubMed, the gold-standard biomedical database maintained by the NIH. We\u2019re actively adding additional scientific sources to broaden coverage. Every citation is verified \u2014 nothing is fabricated or hallucinated.',
  },
  {
    question: 'What does "stance analysis" mean?',
    answer:
      'Each study is evaluated for whether its findings are favorable or adverse to the defense. You\u2019ll see at a glance whether a new paper helps or hurts, without having to read the full text yourself.',
  },
  {
    question: 'Who writes the reports?',
    answer:
      'Reports are generated by AI and then reviewed and curated by our team before delivery. Nothing goes out without human oversight.',
  },
  {
    question: 'How often are reports delivered?',
    answer:
      'Weekly. You\u2019ll receive a report covering all relevant publications from the prior week.',
  },
  {
    question: 'Can my associates and paralegals use this?',
    answer:
      'Yes. Every finding is summarized in plain language so non-scientists on your team can engage with the material directly.',
  },
  {
    question: 'Is this just a search tool?',
    answer:
      'No. Unlike PubMed or Google Scholar, Knowledge Horizon comes to you. You don\u2019t search \u2014 we deliver curated, analyzed intelligence on a recurring basis.',
  },
  {
    question: 'What is Ira?',
    answer:
      'Ira is our AI assistant built into the platform. You can ask Ira questions about the science \u2014 what a study found, why it matters for your case, how it compares to other research \u2014 and get clear, sourced answers grounded in the actual articles. Ira can also help you navigate the platform itself, answer questions about features, and guide you through workflows.',
  },
  {
    question: 'What can I ask Ira?',
    answer:
      'Questions about the science: explain a study\u2019s methodology, summarize findings, identify weaknesses in an adverse paper, or find connections across publications. You can also ask whether any key authors in the space have published on the topic of a given article or theme in the current report. And if you need help with the platform itself \u2014 how to set up a research stream, what a feature does, where to find something \u2014 Ira handles that too.',
  },
  {
    question: 'Do I still need my scientific experts?',
    answer:
      'Absolutely. Knowledge Horizon doesn\u2019t replace expert judgment \u2014 it amplifies it. Your experts get a weekly head start with pre-analyzed literature so they can focus on interpretation and strategy instead of searching journals. Many of our users are consulting experts themselves.',
  },
  {
    question: 'Is my data private?',
    answer:
      'Yes. Your notes, starred articles, and research activity are visible only to your organization.',
  },
  {
    question: 'How do I get started?',
    answer:
      'Request access and we\u2019ll set you up with a free trial.',
  },
];

const features = [
  {
    icon: MagnifyingGlassIcon,
    title: 'Literature Surveillance',
    description:
      'New asbestos, talc, and genetic predisposition publications captured the week they appear \u2014 no manual searching, every citation verified against PubMed.',
  },
  {
    icon: SparklesIcon,
    title: 'AI-Powered Conversation',
    description:
      'Don\u2019t just read the science \u2014 interrogate it. Our AI chat lets you query the week\u2019s literature the way you\u2019d question a witness: targeted, strategic, and on your terms.',
  },
  {
    icon: ScaleIcon,
    title: 'Stance Analysis',
    description:
      'Every study analyzed for litigation implications \u2014 favorable or adverse \u2014 so you know what it means for your case without reading every abstract.',
  },
  {
    icon: LanguageIcon,
    title: 'Scientific Translation',
    description:
      'Technical findings translated into plain language \u2014 so litigators can assess the science, evaluate expert positions, and make strategic decisions quickly and efficiently.',
  },
];

export default function LandingPage() {
  const { isDarkMode, toggleTheme } = useTheme();
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  return (
    <div className="min-h-screen flex flex-col bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100">
      {/* Navbar */}
      <nav className="flex-shrink-0 sticky top-0 z-50 bg-white/80 dark:bg-gray-900/80 backdrop-blur border-b border-gray-200 dark:border-gray-700">
        <div className="max-w-5xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <img src="/logos/KH Icon black.png" alt="Logo" className="h-8 w-auto dark:hidden" />
            <img src="/logos/KH Icon white.png" alt="Logo" className="h-8 w-auto hidden dark:block" />
            <span className="text-lg font-semibold">Knowledge Horizon</span>
          </div>
          <div className="flex items-center gap-4">
            <a
              href="#faq"
              className="text-sm font-medium text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white"
            >
              FAQ
            </a>
            <button
              onClick={toggleTheme}
              className="p-2 rounded-md text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-800"
              aria-label="Toggle theme"
            >
              {isDarkMode ? <SunIcon className="h-5 w-5" /> : <MoonIcon className="h-5 w-5" />}
            </button>
            <Link
              to="/login"
              className="text-sm font-medium text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300"
            >
              Sign In
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="px-6 pt-12 pb-14">
        <div className="max-w-4xl mx-auto text-center">
          <img src="/logos/KH logo black.png" alt="Knowledge Horizon" className="h-16 sm:h-20 w-auto mx-auto mb-5 dark:hidden" />
          <img src="/logos/KH logo white.png" alt="Knowledge Horizon" className="h-16 sm:h-20 w-auto mx-auto mb-5 hidden dark:block" />
          <p className="text-xs font-semibold tracking-[0.25em] text-blue-600 dark:text-blue-400 uppercase mb-4">
            AI-Powered Litigation Intelligence
          </p>
          <h1 className="text-3xl sm:text-4xl font-bold leading-tight">
            Comprehensive Scientific Awareness for Asbestos &amp; Talc Defense
          </h1>

          <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-8 text-left max-w-3xl mx-auto">
            <div>
              <h2 className="text-lg font-semibold mb-2">Curated Weekly Reports</h2>
              <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                Continuous monitoring of the worldwide scientific literature relevant to talc and asbestos litigation, delivered as a curated weekly report.
              </p>
            </div>
            <div>
              <h2 className="text-lg font-semibold mb-2">AI Chat &amp; Analysis</h2>
              <p className="text-gray-600 dark:text-gray-400 leading-relaxed">
                Interact with the scientific literature using our AI-powered tool to rapidly develop critical insights, test arguments, and identify relevant science beyond the weekly report.
              </p>
            </div>
          </div>

          <div className="mt-8 flex flex-wrap gap-4 justify-center">
            <Link
              to="/login"
              className="px-6 py-3 rounded-lg bg-blue-600 text-white font-medium hover:bg-blue-700 transition-colors"
            >
              Sign In
            </Link>
            <a
              href="mailto:cliff@ironcliff.ai?subject=Knowledge%20Horizon%20%E2%80%93%20Access%20Request"
              className="px-6 py-3 rounded-lg border border-gray-300 dark:border-gray-600 font-medium hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
            >
              Request Access
            </a>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="flex-1 bg-gray-50 dark:bg-gray-800/50 py-20 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {features.map((f) => (
              <div
                key={f.title}
                className="bg-white dark:bg-gray-800 rounded-xl p-6 shadow-sm border border-gray-200 dark:border-gray-700"
              >
                <div className="flex items-center gap-3 mb-3">
                  <span className="flex items-center justify-center w-9 h-9 rounded-lg bg-blue-100 dark:bg-blue-900/40 text-blue-600 dark:text-blue-400">
                    <f.icon className="h-5 w-5" />
                  </span>
                  <h3 className="text-lg font-semibold">{f.title}</h3>
                </div>
                <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
                  {f.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="scroll-mt-20 py-20 px-6">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-12">Frequently Asked Questions</h2>
          <div className="space-y-3">
            {faqs.map((faq, i) => (
              <div
                key={i}
                className="border border-gray-200 dark:border-gray-700 rounded-lg overflow-hidden"
              >
                <button
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full flex items-center justify-between px-6 py-4 text-left font-medium hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors"
                >
                  <span>{faq.question}</span>
                  <svg
                    className={`w-5 h-5 flex-shrink-0 ml-4 text-gray-400 transition-transform ${openFaq === i ? 'rotate-180' : ''}`}
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    strokeWidth={2}
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
                {openFaq === i && (
                  <div className="px-6 pb-4 text-gray-600 dark:text-gray-400 leading-relaxed">
                    {faq.answer}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="flex-shrink-0 border-t border-gray-200 dark:border-gray-700 py-8 px-6">
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-gray-500 dark:text-gray-400">
          <span>&copy; {new Date().getFullYear()} Knowledge Horizon. All rights reserved.</span>
          <Link
            to="/login"
            className="text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300 font-medium"
          >
            Sign In
          </Link>
        </div>
      </footer>
    </div>
  );
}
